spring:
  profiles:
    active: dev

# aaa
#启动命令for spark 1.5.1 （指定hadoop、spark、hive、hbase库加载位置，以及xml配置加载位置）
#java -XX:PermSize=512m -XX:MaxPermSize=10240m -Xms1024m -Xmx10240m -Dloader.path="hadoop/conf,hadoop/lib" -Djava.library.path=$HADOOP_PREFIX/lib:$HADOOP_PREFIX/lib/native -Djava.io.tmpdir=./temp/ -jar lambda-manager-1.0.0.jar

#启动命令for spark 2.1.0 （指定hadoop、spark、hive、hbase库加载位置，以及xml配置加载位置）
#java -XX:PermSize=512m -XX:MaxPermSize=10240m -Xms1024m -Xmx10240m -Dloader.path="hadoop/conf,hadoop/lib" -Djava.library.path=$HADOOP_PREFIX/lib:$HADOOP_PREFIX/lib/native -Djava.io.tmpdir=./temp/ -jar lambda-manager-1.0.0.jar

